herbs = {
	"Peacebloom",
	"Silverleaf",
	"Bloodthistle",
	"Earthroot",
	"Mageroyal",
	"Swiftthistle",
	"Briarthorn",
	"Stranglekelp",
	"Bruiseweed",
	"Grave Moss",
	"Wild Steelbloom",
	"Kingsblood",
	"Liferoot",
	"Fadeleaf",
	"Goldthorn",
	"Khadgar's Whisker",
	"Dragon's Teeth",
	"Firebloom",
	"Purple Lotus",
	"Wildvine",
	"Arthas' Tears",
	"Sungrass",
	"Blindweed",
	"Ghost Mushroom",
	"Gromsblood",
	"Golden Sansam",
	"Dreamfoil",
	"Mountain Silversage",
	"Sorrowmoss",
	"Icecap",
	"Black Lotus",
	"Felweed",
	"Dreaming Glory",
	"Ragveil",
	"Flame Cap",
	"Terocone",
	"Ancient Lichen",
	"Netherbloom",
	"Netherdust Bush",
	"Nightmare Vine",
	"Mana Thistle",
	"Fel Lotus",
	"Goldclover",
	"Fire Leaf",
	"Tiger Lily",
	"Talandra's Rose",
	"Frozen Herb",
	"Adder's Tongue",
	"Deadnettle",
	"Lichbloom",
	"Icethorn",
	"Frost Lotus",
	"Cinderbloom",
	"Azshara's Veil",
	"Stormvine",
	"Heartblossom",
	"Whiptail",
	"Twilight Jasmine",
	"Green Tea Leaf",
	"Rain Poppy",
	"Silkweed",
	"Snow Lily",
	"Fool's Cap",
	"Golden Lotus (herb)",
	"Sha-Touched Herb",
	"Desecrated Herb",
	"Frostweed",
	"Starflower",
	"Fireweed",
	"Gorgrond Flytrap",
	"Talador Orchid",
	"Nagrand Arrowbloom",
	"Aethril",
	"Dreamleaf",
	"Felwort",
	"Fjarnskaggl",
	"Foxflower",
	"Starlight Rose",
}